language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
install:
- npm install -g npm@6.10.1
- npm ci
script:
- npm run lint
- npm run test
- npm run build
before_deploy:
- ssh-keyscan -t rsa -H $DEPLOY_HOST 2>&1 | tee -a $TRAVIS_HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa 
deploy:
  - provider: script   
    skip_cleanup: true   
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/out/ travis@$DEPLOY_HOST:/var/www/html/demo-main 
    on:
      branch: main
  - provider: script   
    skip_cleanup: true   
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/out/ travis@$DEPLOY_HOST:/var/www/html/demo-staging 
    on:
      branch: staging 
